# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:37:10+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class YoutubeActorInfo(BaseModel):
    channelId: Optional[str] = Field(
        None, description='ID of the YouTube channel owned by the Actor.'
    )


class ClientSpecificActorInfo(BaseModel):
    youtubeActorInfo: Optional[YoutubeActorInfo] = Field(
        None, description='Actor info specific to YouTube clients.'
    )


class Image(BaseModel):
    url: Optional[str] = Field(
        None,
        description="The URL of the actor's profile photo. To resize the image and crop it to a square, append the query string ?sz=x, where x is the dimension in pixels of each side.",
    )


class Name(BaseModel):
    familyName: Optional[str] = Field(
        None, description='The family name ("last name") of the actor.'
    )
    givenName: Optional[str] = Field(
        None, description='The given name ("first name") of the actor.'
    )


class Verification(BaseModel):
    adHocVerified: Optional[str] = Field(
        None, description='Verification for one-time or manual processes.'
    )


class Actor(BaseModel):
    clientSpecificActorInfo: Optional[ClientSpecificActorInfo] = Field(
        None, description='Actor info specific to particular clients.'
    )
    displayName: Optional[str] = Field(
        None, description='The name of the actor, suitable for display.'
    )
    id: Optional[str] = Field(
        None, description="The ID of the actor's Person resource."
    )
    image: Optional[Image] = Field(
        None, description='The image representation of the actor.'
    )
    name: Optional[Name] = Field(
        None,
        description='An object representation of the individual components of name.',
    )
    url: Optional[str] = Field(
        None, description="The link to the actor's Google profile."
    )
    verification: Optional[Verification] = Field(
        None, description='Verification status of actor.'
    )


class ClientSpecificActorInfo1(BaseModel):
    youtubeActorInfo: Optional[YoutubeActorInfo] = Field(
        None, description='Actor info specific to YouTube clients.'
    )


class Image1(BaseModel):
    url: Optional[str] = Field(
        None,
        description='A URL that points to a thumbnail photo of the original actor.',
    )


class Actor1(BaseModel):
    clientSpecificActorInfo: Optional[ClientSpecificActorInfo1] = Field(
        None, description='Actor info specific to particular clients.'
    )
    displayName: Optional[str] = Field(
        None, description="The original actor's name, which is suitable for display."
    )
    id: Optional[str] = Field(None, description='ID of the original actor.')
    image: Optional[Image1] = Field(
        None, description='The image representation of the original actor.'
    )
    url: Optional[str] = Field(
        None, description="A link to the original actor's Google profile."
    )
    verification: Optional[Verification] = Field(
        None, description='Verification status of actor.'
    )


class Embed(BaseModel):
    type: Optional[str] = Field(None, description='Media type of the link.')
    url: Optional[str] = Field(None, description='URL of the link.')


class FullImage(BaseModel):
    height: Optional[int] = Field(
        None, description='The height, in pixels, of the linked resource.'
    )
    type: Optional[str] = Field(None, description='Media type of the link.')
    url: Optional[str] = Field(None, description='URL of the image.')
    width: Optional[int] = Field(
        None, description='The width, in pixels, of the linked resource.'
    )


class Image2(BaseModel):
    height: Optional[int] = Field(
        None, description='The height, in pixels, of the linked resource.'
    )
    type: Optional[str] = Field(None, description='Media type of the link.')
    url: Optional[str] = Field(None, description='Image URL.')
    width: Optional[int] = Field(
        None, description='The width, in pixels, of the linked resource.'
    )


class Image3(BaseModel):
    height: Optional[int] = Field(
        None, description='The height, in pixels, of the linked resource.'
    )
    type: Optional[str] = Field(None, description='Media type of the link.')
    url: Optional[str] = Field(None, description='Image url.')
    width: Optional[int] = Field(
        None, description='The width, in pixels, of the linked resource.'
    )


class Thumbnail(BaseModel):
    description: Optional[str] = Field(
        None, description='Potential name of the thumbnail.'
    )
    image: Optional[Image3] = Field(None, description='Image resource.')
    url: Optional[str] = Field(
        None, description='URL of the webpage containing the image.'
    )


class Attachment(BaseModel):
    content: Optional[str] = Field(
        None,
        description='If the attachment is an article, this property contains a snippet of text from the article. It can also include descriptions for other types.',
    )
    displayName: Optional[str] = Field(
        None,
        description='The title of the attachment, such as a photo caption or an article title.',
    )
    embed: Optional[Embed] = Field(
        None, description='If the attachment is a video, the embeddable link.'
    )
    fullImage: Optional[FullImage] = Field(
        None, description='The full image URL for photo attachments.'
    )
    id: Optional[str] = Field(None, description='The ID of the attachment.')
    image: Optional[Image2] = Field(
        None, description='The preview image for photos or videos.'
    )
    objectType: Optional[str] = Field(
        None,
        description='The type of media object. Possible values include, but are not limited to, the following values:  \n- "photo" - A photo. \n- "album" - A photo album. \n- "video" - A video. \n- "article" - An article, specified by a link.',
    )
    thumbnails: Optional[List[Thumbnail]] = Field(
        None,
        description='If the attachment is an album, this property is a list of potential additional thumbnails from the album.',
    )
    url: Optional[str] = Field(
        None,
        description='The link to the attachment, which should be of type text/html.',
    )


class Plusoners(BaseModel):
    selfLink: Optional[str] = Field(
        None, description="The URL for the collection of people who +1'd this activity."
    )
    totalItems: Optional[int] = Field(
        None, description="Total number of people who +1'd this activity."
    )


class Replies(BaseModel):
    selfLink: Optional[str] = Field(
        None,
        description='The URL for the collection of comments in reply to this activity.',
    )
    totalItems: Optional[int] = Field(
        None, description='Total number of comments on this activity.'
    )


class Resharers(BaseModel):
    selfLink: Optional[str] = Field(
        None, description='The URL for the collection of resharers.'
    )
    totalItems: Optional[int] = Field(
        None, description='Total number of people who reshared this activity.'
    )


class Object(BaseModel):
    actor: Optional[Actor1] = Field(
        None,
        description="If this activity's object is itself another activity, such as when a person reshares an activity, this property specifies the original activity's actor.",
    )
    attachments: Optional[List[Attachment]] = Field(
        None, description='The media objects attached to this activity.'
    )
    content: Optional[str] = Field(
        None, description='The HTML-formatted content, which is suitable for display.'
    )
    id: Optional[str] = Field(
        None,
        description='The ID of the object. When resharing an activity, this is the ID of the activity that is being reshared.',
    )
    objectType: Optional[str] = Field(
        None,
        description='The type of the object. Possible values include, but are not limited to, the following values:  \n- "note" - Textual content. \n- "activity" - A Google+ activity.',
    )
    originalContent: Optional[str] = Field(
        None,
        description='The content (text) as provided by the author, which is stored without any HTML formatting. When creating or updating an activity, this value must be supplied as plain text in the request.',
    )
    plusoners: Optional[Plusoners] = Field(
        None, description="People who +1'd this activity."
    )
    replies: Optional[Replies] = Field(
        None, description='Comments in reply to this activity.'
    )
    resharers: Optional[Resharers] = Field(
        None, description='People who reshared this activity.'
    )
    url: Optional[str] = Field(
        None, description='The URL that points to the linked resource.'
    )


class Provider(BaseModel):
    title: Optional[str] = Field(None, description='Name of the service provider.')


class ClientSpecificActorInfo2(BaseModel):
    youtubeActorInfo: Optional[YoutubeActorInfo] = Field(
        None, description='Actor info specific to YouTube clients.'
    )


class Image4(BaseModel):
    url: Optional[str] = Field(
        None,
        description="The URL of the actor's profile photo. To resize the image and crop it to a square, append the query string ?sz=x, where x is the dimension in pixels of each side.",
    )


class Actor2(BaseModel):
    clientSpecificActorInfo: Optional[ClientSpecificActorInfo2] = Field(
        None, description='Actor info specific to particular clients.'
    )
    displayName: Optional[str] = Field(
        None, description='The name of this actor, suitable for display.'
    )
    id: Optional[str] = Field(None, description='The ID of the actor.')
    image: Optional[Image4] = Field(
        None, description='The image representation of this actor.'
    )
    url: Optional[str] = Field(
        None, description='A link to the Person resource for this actor.'
    )
    verification: Optional[Verification] = Field(
        None, description='Verification status of actor.'
    )


class InReplyToItem(BaseModel):
    id: Optional[str] = Field(None, description='The ID of the activity.')
    url: Optional[str] = Field(None, description='The URL of the activity.')


class Object1(BaseModel):
    content: Optional[str] = Field(
        None, description='The HTML-formatted content, suitable for display.'
    )
    objectType: Optional[str] = Field(
        'comment',
        description='The object type of this comment. Possible values are:  \n- "comment" - A comment in reply to an activity.',
    )
    originalContent: Optional[str] = Field(
        None,
        description='The content (text) as provided by the author, stored without any HTML formatting. When creating or updating a comment, this value must be supplied as plain text in the request.',
    )


class Plusoners1(BaseModel):
    totalItems: Optional[int] = Field(
        None, description="Total number of people who +1'd this comment."
    )


class Comment(BaseModel):
    actor: Optional[Actor2] = Field(
        None, description='The person who posted this comment.'
    )
    etag: Optional[str] = Field(
        None, description='ETag of this response for caching purposes.'
    )
    id: Optional[str] = Field(None, description='The ID of this comment.')
    inReplyTo: Optional[List[InReplyToItem]] = Field(
        None, description='The activity this comment replied to.'
    )
    kind: Optional[str] = Field(
        'plus#comment',
        description='Identifies this resource as a comment. Value: "plus#comment".',
    )
    object: Optional[Object1] = Field(None, description='The object of this comment.')
    plusoners: Optional[Plusoners1] = Field(
        None, description="People who +1'd this comment."
    )
    published: Optional[datetime] = Field(
        None,
        description='The time at which this comment was initially published. Formatted as an RFC 3339 timestamp.',
    )
    selfLink: Optional[str] = Field(None, description='Link to this comment resource.')
    updated: Optional[datetime] = Field(
        None,
        description='The time at which this comment was last updated. Formatted as an RFC 3339 timestamp.',
    )
    verb: Optional[str] = Field(
        'post',
        description='This comment\'s verb, indicating what action was performed. Possible values are:  \n- "post" - Publish content to the stream.',
    )


class CommentFeed(BaseModel):
    etag: Optional[str] = Field(
        None, description='ETag of this response for caching purposes.'
    )
    id: Optional[str] = Field(
        None, description='The ID of this collection of comments.'
    )
    items: Optional[List[Comment]] = Field(
        None, description='The comments in this page of results.'
    )
    kind: Optional[str] = Field(
        'plus#commentFeed',
        description='Identifies this resource as a collection of comments. Value: "plus#commentFeed".',
    )
    nextLink: Optional[str] = Field(
        None, description='Link to the next page of activities.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='The continuation token, which is used to page through large result sets. Provide this value in a subsequent request to return the next page of results.',
    )
    title: Optional[str] = Field(
        None, description='The title of this collection of comments.'
    )
    updated: Optional[datetime] = Field(
        None,
        description='The time at which this collection of comments was last updated. Formatted as an RFC 3339 timestamp.',
    )


class AgeRange(BaseModel):
    max: Optional[int] = Field(
        None,
        description='The age range\'s upper bound, if any. Possible values include, but are not limited to, the following:  \n- "17" - for age 17 \n- "20" - for age 20',
    )
    min: Optional[int] = Field(
        None,
        description='The age range\'s lower bound, if any. Possible values include, but are not limited to, the following:  \n- "21" - for age 21 \n- "18" - for age 18',
    )


class CoverInfo(BaseModel):
    leftImageOffset: Optional[int] = Field(
        None,
        description='The difference between the left position of the cover image and the actual displayed cover image. Only valid for banner layout.',
    )
    topImageOffset: Optional[int] = Field(
        None,
        description='The difference between the top position of the cover image and the actual displayed cover image. Only valid for banner layout.',
    )


class CoverPhoto(BaseModel):
    height: Optional[int] = Field(None, description='The height of the image.')
    url: Optional[str] = Field(None, description='The URL of the image.')
    width: Optional[int] = Field(None, description='The width of the image.')


class Cover(BaseModel):
    coverInfo: Optional[CoverInfo] = Field(
        None, description='Extra information about the cover photo.'
    )
    coverPhoto: Optional[CoverPhoto] = Field(
        None, description="The person's primary cover image."
    )
    layout: Optional[str] = Field(
        None,
        description='The layout of the cover art. Possible values include, but are not limited to, the following values:  \n- "banner" - One large image banner.',
    )


class Email(BaseModel):
    type: Optional[str] = Field(
        None,
        description='The type of address. Possible values include, but are not limited to, the following values:  \n- "account" - Google account email address. \n- "home" - Home email address. \n- "work" - Work email address. \n- "other" - Other.',
    )
    value: Optional[str] = Field(None, description='The email address.')


class Image5(BaseModel):
    isDefault: Optional[bool] = Field(
        None, description="Whether the person's profile photo is the default one"
    )
    url: Optional[str] = Field(
        None,
        description="The URL of the person's profile photo. To resize the image and crop it to a square, append the query string ?sz=x, where x is the dimension in pixels of each side.",
    )


class Name1(BaseModel):
    familyName: Optional[str] = Field(
        None, description='The family name (last name) of this person.'
    )
    formatted: Optional[str] = Field(
        None,
        description='The full name of this person, including middle names, suffixes, etc.',
    )
    givenName: Optional[str] = Field(
        None, description='The given name (first name) of this person.'
    )
    honorificPrefix: Optional[str] = Field(
        None,
        description='The honorific prefixes (such as "Dr." or "Mrs.") for this person.',
    )
    honorificSuffix: Optional[str] = Field(
        None, description='The honorific suffixes (such as "Jr.") for this person.'
    )
    middleName: Optional[str] = Field(
        None, description='The middle name of this person.'
    )


class Organization(BaseModel):
    department: Optional[str] = Field(
        None, description='The department within the organization. Deprecated.'
    )
    description: Optional[str] = Field(
        None,
        description="A short description of the person's role in this organization. Deprecated.",
    )
    endDate: Optional[str] = Field(
        None, description='The date that the person left this organization.'
    )
    location: Optional[str] = Field(
        None, description='The location of this organization. Deprecated.'
    )
    name: Optional[str] = Field(None, description='The name of the organization.')
    primary: Optional[bool] = Field(
        None,
        description='If "true", indicates this organization is the person\'s primary one, which is typically interpreted as the current one.',
    )
    startDate: Optional[str] = Field(
        None, description='The date that the person joined this organization.'
    )
    title: Optional[str] = Field(
        None, description="The person's job title or role within the organization."
    )
    type: Optional[str] = Field(
        None,
        description='The type of organization. Possible values include, but are not limited to, the following values:  \n- "work" - Work. \n- "school" - School.',
    )


class PlacesLivedItem(BaseModel):
    primary: Optional[bool] = Field(
        None,
        description='If "true", this place of residence is this person\'s primary residence.',
    )
    value: Optional[str] = Field(
        None,
        description='A place where this person has lived. For example: "Seattle, WA", "Near Toronto".',
    )


class Url(BaseModel):
    label: Optional[str] = Field(None, description='The label of the URL.')
    type: Optional[str] = Field(
        None,
        description='The type of URL. Possible values include, but are not limited to, the following values:  \n- "otherProfile" - URL for another profile. \n- "contributor" - URL to a site for which this person is a contributor. \n- "website" - URL for this Google+ Page\'s primary website. \n- "other" - Other URL.',
    )
    value: Optional[str] = Field(None, description='The URL value.')


class Person(BaseModel):
    aboutMe: Optional[str] = Field(
        None, description='A short biography for this person.'
    )
    ageRange: Optional[AgeRange] = Field(
        None,
        description="The age range of the person. Valid ranges are 17 or younger, 18 to 20, and 21 or older. Age is determined from the user's birthday using Western age reckoning.",
    )
    birthday: Optional[str] = Field(
        None, description="The person's date of birth, represented as YYYY-MM-DD."
    )
    braggingRights: Optional[str] = Field(
        None, description='The "bragging rights" line of this person.'
    )
    circledByCount: Optional[int] = Field(
        None,
        description='For followers who are visible, the number of people who have added this person or page to a circle.',
    )
    cover: Optional[Cover] = Field(None, description='The cover photo content.')
    currentLocation: Optional[str] = Field(
        None, description='(this field is not currently used)'
    )
    displayName: Optional[str] = Field(
        None, description='The name of this person, which is suitable for display.'
    )
    domain: Optional[str] = Field(
        None,
        description="The hosted domain name for the user's Google Apps account. For instance, example.com. The plus.profile.emails.read or email scope is needed to get this domain name.",
    )
    emails: Optional[List[Email]] = Field(
        None,
        description='A list of email addresses that this person has, including their Google account email address, and the public verified email addresses on their Google+ profile. The plus.profile.emails.read scope is needed to retrieve these email addresses, or the email scope can be used to retrieve just the Google account email address.',
    )
    etag: Optional[str] = Field(
        None, description='ETag of this response for caching purposes.'
    )
    gender: Optional[str] = Field(
        None,
        description='The person\'s gender. Possible values include, but are not limited to, the following values:  \n- "male" - Male gender. \n- "female" - Female gender. \n- "other" - Other.',
    )
    id: Optional[str] = Field(None, description='The ID of this person.')
    image: Optional[Image5] = Field(
        None, description="The representation of the person's profile photo."
    )
    isPlusUser: Optional[bool] = Field(
        None, description='Whether this user has signed up for Google+.'
    )
    kind: Optional[str] = Field(
        'plus#person',
        description='Identifies this resource as a person. Value: "plus#person".',
    )
    language: Optional[str] = Field(
        None, description="The user's preferred language for rendering."
    )
    name: Optional[Name1] = Field(
        None,
        description="An object representation of the individual components of a person's name.",
    )
    nickname: Optional[str] = Field(None, description='The nickname of this person.')
    objectType: Optional[str] = Field(
        None,
        description='Type of person within Google+. Possible values include, but are not limited to, the following values:  \n- "person" - represents an actual person. \n- "page" - represents a page.',
    )
    occupation: Optional[str] = Field(
        None, description='The occupation of this person.'
    )
    organizations: Optional[List[Organization]] = Field(
        None,
        description='A list of current or past organizations with which this person is associated.',
    )
    placesLived: Optional[List[PlacesLivedItem]] = Field(
        None, description='A list of places where this person has lived.'
    )
    plusOneCount: Optional[int] = Field(
        None,
        description="If a Google+ Page, the number of people who have +1'd this page.",
    )
    relationshipStatus: Optional[str] = Field(
        None,
        description='The person\'s relationship status. Possible values include, but are not limited to, the following values:  \n- "single" - Person is single. \n- "in_a_relationship" - Person is in a relationship. \n- "engaged" - Person is engaged. \n- "married" - Person is married. \n- "its_complicated" - The relationship is complicated. \n- "open_relationship" - Person is in an open relationship. \n- "widowed" - Person is widowed. \n- "in_domestic_partnership" - Person is in a domestic partnership. \n- "in_civil_union" - Person is in a civil union.',
    )
    skills: Optional[str] = Field(None, description="The person's skills.")
    tagline: Optional[str] = Field(
        None, description='The brief description (tagline) of this person.'
    )
    url: Optional[str] = Field(None, description="The URL of this person's profile.")
    urls: Optional[List[Url]] = Field(
        None, description='A list of URLs for this person.'
    )
    verified: Optional[bool] = Field(
        None, description='Whether the person or Google+ Page has been verified.'
    )


class Address(BaseModel):
    formatted: Optional[str] = Field(
        None, description='The formatted address for display.'
    )


class Position(BaseModel):
    latitude: Optional[float] = Field(
        None, description='The latitude of this position.'
    )
    longitude: Optional[float] = Field(
        None, description='The longitude of this position.'
    )


class Place(BaseModel):
    address: Optional[Address] = Field(
        None, description='The physical address of the place.'
    )
    displayName: Optional[str] = Field(
        None, description='The display name of the place.'
    )
    id: Optional[str] = Field(None, description='The id of the place.')
    kind: Optional[str] = Field(
        'plus#place',
        description='Identifies this resource as a place. Value: "plus#place".',
    )
    position: Optional[Position] = Field(None, description='The position of the place.')


class PlusAclentryResource(BaseModel):
    displayName: Optional[str] = Field(
        None, description='A descriptive name for this entry. Suitable for display.'
    )
    id: Optional[str] = Field(
        None,
        description='The ID of the entry. For entries of type "person" or "circle", this is the ID of the resource. For other types, this property is not set.',
    )
    type: Optional[str] = Field(
        None,
        description='The type of entry describing to whom access is granted. Possible values are:  \n- "person" - Access to an individual. \n- "circle" - Access to members of a circle. \n- "myCircles" - Access to members of all the person\'s circles. \n- "extendedCircles" - Access to members of all the person\'s circles, plus all of the people in their circles. \n- "domain" - Access to members of the person\'s Google Apps domain. \n- "public" - Access to anyone on the web.',
    )


class OrderBy(Enum):
    best = 'best'
    recent = 'recent'


class Alt(Enum):
    json = 'json'


class SortOrder(Enum):
    ascending = 'ascending'
    descending = 'descending'


class Collection(Enum):
    plusoners = 'plusoners'
    resharers = 'resharers'


class Collection1(Enum):
    public = 'public'


class OrderBy2(Enum):
    alphabetical = 'alphabetical'
    best = 'best'


class Collection2(Enum):
    connected = 'connected'
    visible = 'visible'


class Acl(BaseModel):
    description: Optional[str] = Field(
        None, description='Description of the access granted, suitable for display.'
    )
    items: Optional[List[PlusAclentryResource]] = Field(
        None, description='The list of access entries.'
    )
    kind: Optional[str] = Field(
        'plus#acl',
        description='Identifies this resource as a collection of access controls. Value: "plus#acl".',
    )


class Activity(BaseModel):
    access: Optional[Acl] = Field(
        None, description='Identifies who has access to see this activity.'
    )
    actor: Optional[Actor] = Field(
        None, description='The person who performed this activity.'
    )
    address: Optional[str] = Field(
        None, description='Street address where this activity occurred.'
    )
    annotation: Optional[str] = Field(
        None,
        description='Additional content added by the person who shared this activity, applicable only when resharing an activity.',
    )
    crosspostSource: Optional[str] = Field(
        None,
        description='If this activity is a crosspost from another system, this property specifies the ID of the original activity.',
    )
    etag: Optional[str] = Field(
        None, description='ETag of this response for caching purposes.'
    )
    geocode: Optional[str] = Field(
        None,
        description='Latitude and longitude where this activity occurred. Format is latitude followed by longitude, space separated.',
    )
    id: Optional[str] = Field(None, description='The ID of this activity.')
    kind: Optional[str] = Field(
        'plus#activity',
        description='Identifies this resource as an activity. Value: "plus#activity".',
    )
    location: Optional[Place] = Field(
        None, description='The location where this activity occurred.'
    )
    object: Optional[Object] = Field(None, description='The object of this activity.')
    placeId: Optional[str] = Field(
        None, description='ID of the place where this activity occurred.'
    )
    placeName: Optional[str] = Field(
        None, description='Name of the place where this activity occurred.'
    )
    provider: Optional[Provider] = Field(
        None, description='The service provider that initially published this activity.'
    )
    published: Optional[datetime] = Field(
        None,
        description='The time at which this activity was initially published. Formatted as an RFC 3339 timestamp.',
    )
    radius: Optional[str] = Field(
        None,
        description='Radius, in meters, of the region where this activity occurred, centered at the latitude and longitude identified in geocode.',
    )
    title: Optional[str] = Field(None, description='Title of this activity.')
    updated: Optional[datetime] = Field(
        None,
        description='The time at which this activity was last updated. Formatted as an RFC 3339 timestamp.',
    )
    url: Optional[str] = Field(None, description='The link to this activity.')
    verb: Optional[str] = Field(
        None,
        description='This activity\'s verb, which indicates the action that was performed. Possible values include, but are not limited to, the following values:  \n- "post" - Publish content to the stream. \n- "share" - Reshare an activity.',
    )


class ActivityFeed(BaseModel):
    etag: Optional[str] = Field(
        None, description='ETag of this response for caching purposes.'
    )
    id: Optional[str] = Field(
        None, description='The ID of this collection of activities. Deprecated.'
    )
    items: Optional[List[Activity]] = Field(
        None, description='The activities in this page of results.'
    )
    kind: Optional[str] = Field(
        'plus#activityFeed',
        description='Identifies this resource as a collection of activities. Value: "plus#activityFeed".',
    )
    nextLink: Optional[str] = Field(
        None, description='Link to the next page of activities.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='The continuation token, which is used to page through large result sets. Provide this value in a subsequent request to return the next page of results.',
    )
    selfLink: Optional[str] = Field(None, description='Link to this activity resource.')
    title: Optional[str] = Field(
        None,
        description='The title of this collection of activities, which is a truncated portion of the content.',
    )
    updated: Optional[datetime] = Field(
        None,
        description='The time at which this collection of activities was last updated. Formatted as an RFC 3339 timestamp.',
    )


class PeopleFeed(BaseModel):
    etag: Optional[str] = Field(
        None, description='ETag of this response for caching purposes.'
    )
    items: Optional[List[Person]] = Field(
        None,
        description='The people in this page of results. Each item includes the id, displayName, image, and url for the person. To retrieve additional profile data, see the people.get method.',
    )
    kind: Optional[str] = Field(
        'plus#peopleFeed',
        description='Identifies this resource as a collection of people. Value: "plus#peopleFeed".',
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='The continuation token, which is used to page through large result sets. Provide this value in a subsequent request to return the next page of results.',
    )
    selfLink: Optional[str] = Field(None, description='Link to this resource.')
    title: Optional[str] = Field(
        None, description='The title of this collection of people.'
    )
    totalItems: Optional[int] = Field(
        None,
        description='The total number of people available in this list. The number of people in a response might be smaller due to paging. This might not be set for all collections.',
    )
